### ISSUE TITLE
Setting lost on backup/restore and copy

### ISSUE THREAD

**Issue by leonstr** [rigao-alexandre/moodle-quizaccess_failgrade#10]
### Steps to reproduce issue:

1. Create a course.
2. Add a quiz to the course setting _Block extra attempts if passing grade_ to Yes.
3. Back up the course.
4. Restore the course as a new course.
5. In the restored/new course view the quiz settings.

### Expected results:

_Block extra attempts if passing grade_ is Yes.

### Actual results:

_Block extra attempts if passing grade_ is No.

**Comment by rigao-alexandre** [comment]
Merge!
