### ISSUE TITLE
typos in lang strings

### ISSUE THREAD

**Issue by danmarsden** [rigao-alexandre/moodle-quizaccess_failgrade#2]
$string['failgradeenabled_help'] = 'If enabled, a student must not have a psssing grade to attempt the quiz more times.';
$string['failgradedescription'] = 'Attempts avaliables till reaching passing grade.';

should be more like:
$string['failgradeenabled_help'] = 'If enabled, a student must not have a passing grade to attempt the quiz more times.';
$string['failgradedescription'] = 'Attempts available untill reaching passing grade.';

**Comment by danmarsden** [comment]
failgreadeenabled_help might read better as:
Prevent user from attempting the quiz again once they have receiving a passing grade.

**Comment by rigao-alexandre** [comment]
@danmarsden thanks for the feedback and suggestions. Please check af7fa7a !
