### ISSUE TITLE
String MISSING in AMOS

### ISSUE THREAD

**Issue by dinism** [rigao-alexandre/moodle-quizaccess_failgrade#4]
Thanks for the plugin
I'm PT-PT translator.
This string is missing in AMOS. Can't translate:
![imagem](https://user-images.githubusercontent.com/14828021/89011470-4e97ed00-d308-11ea-988c-938f5fbb37a1.png)
OBRIGADO pelo plugin!! 👍

**Comment by rigao-alexandre** [comment]
@dinism obrigado pelo feedback!

Essa string mudou no commit af7fa7a . Pode validar, por favor?

**Comment by dinism** [comment]
Confirmado. 
Obrigado pelo plugin. 
Em PT-PT ficou assim:
![imagem](https://user-images.githubusercontent.com/14828021/89069430-05c55000-d36b-11ea-9ae7-2fe75e997494.png)
Acha que está bem?

**Comment by rigao-alexandre** [comment]
@dinism opa, estão excelentes as traduções!

Você pode me informar se é permitido eu incorporar as traduções do AMOS no meu plugin?

**Comment by dinism** [comment]
Se for as minhas traduções, FAZ FAVOR. Claro que podes usar.
Quid pro quo.
OBRIGADO pelo plugin (usamos módulo em PT-PT)
