### ISSUE TITLE
PHP Notice: Trying to get property 'userid' of non-object

### ISSUE THREAD

**Issue by leonstr** [rigao-alexandre/moodle-quizaccess_failgrade#7]
On Moodle 3.9.10+ (Build: 20210924) with debugging enabled (debug: DEVELOPER, debugdisplay: Yes) when the learner clicks on the quiz activity (mod/quiz/view.php?id=...) with this accessrule enabled the following errors appear at the top of the page:

 Notice: Trying to get property 'userid' of non-object in /var/www/moodle/mod/quiz/accessrule/failgrade/rule.php on line 72

 Notice: Trying to get property 'userid' of non-object in /var/www/moodle/mod/quiz/accessrule/failgrade/rule.php on line 74

 Notice: Trying to get property 'userid' of non-object in /var/www/moodle/mod/quiz/accessrule/failgrade/rule.php on line 72

 Notice: Trying to get property 'userid' of non-object in /var/www/moodle/mod/quiz/accessrule/failgrade/rule.php on line 74

**Comment by leonstr** [comment]
Pull request added: https://github.com/rigao-alexandre/moodle-quizaccess_failgrade/pull/8

**Comment by rigao-alexandre** [comment]
@leonstr thanks for the contribution!

I just accepted the PR and I intend to release a new version by the end of this week, updating to the new version of Moodle
