### ISSUE TITLE
Moodle 4 support

### ISSUE THREAD

**Issue by acquaalta** [rigao-alexandre/moodle-quizaccess_failgrade#9]
Hi,
Could you please add support for Moodle 4?
Even if the current version of the plugin would work on Moodle 4, an official support would be great.

Thanks even for considering it :-)

**Comment by rigao-alexandre** [comment]
@acquaalta hey, thanks for your suggestion!

Have you tested the plugin in the V4? Did you find any bugs?

I'll do some testing also, of course, but just checking for some feedback!
